#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")

echo updating repository
cd $parentdir
git reset --hard > /dev/null 2>&1
git pull origin main > /dev/null 2>&1

echo setting permissions
bash $parentdir/functions/function_configure_permissions